# Generated by Django 4.0.4 on 2022-08-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0004_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.CharField(blank=True, default='Untitled', max_length=300, null=True),
        ),
    ]
