# Generated by Django 4.0.4 on 2022-08-31 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0006_user_details_verifield'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites_id', models.CharField(max_length=200)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft_address_id', to='nftapi.user_details')),
            ],
        ),
    ]
