# Generated by Django 4.0.4 on 2022-08-31 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0007_user_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_favorite',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_address_id', to='nftapi.user_details'),
        ),
    ]
