# Generated by Django 4.0.4 on 2022-08-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0009_alter_user_details_profile_header_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='address',
            new_name='address_id',
        ),
    ]
