# Generated by Django 4.0.4 on 2022-08-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0010_rename_address_user_details_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_followers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_followers',
            name='followers',
        ),
        migrations.DeleteModel(
            name='User_favorite',
        ),
        migrations.DeleteModel(
            name='User_followers',
        ),
    ]
