# Generated by Django 4.0.4 on 2022-09-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0012_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_followers',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, to='nftapi.user_details'),
        ),
    ]
