# Generated by Django 4.0.4 on 2022-09-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0013_alter_user_followers_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_followers',
            name='followers',
            field=models.ManyToManyField(blank=True, to='nftapi.user_details'),
        ),
        migrations.CreateModel(
            name='User_favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites_id', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_address_id', to='nftapi.user_details')),
            ],
        ),
    ]
