# Generated by Django 4.0.4 on 2022-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0014_alter_user_followers_followers_user_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='env_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.CharField(max_length=200)),
                ('string2', models.CharField(max_length=200)),
                ('string3', models.CharField(max_length=200)),
                ('string4', models.CharField(max_length=200)),
            ],
        ),
    ]
