# Generated by Django 4.0.4 on 2022-10-06 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0015_env_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_favorite',
            old_name='address',
            new_name='user_id',
        ),
    ]
