# Generated by Django 4.0.4 on 2022-10-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0016_rename_address_user_favorite_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_favorite',
            old_name='user_id',
            new_name='address',
        ),
    ]
