# Generated by Django 4.0.4 on 2022-10-06 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0017_rename_user_id_user_favorite_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_followers',
            old_name='address',
            new_name='username',
        ),
    ]
