# Generated by Django 4.0.4 on 2022-10-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0018_rename_address_user_followers_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_followers',
            old_name='username',
            new_name='address',
        ),
    ]
