# Generated by Django 4.0.4 on 2022-10-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0019_rename_username_user_followers_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_followers',
            old_name='address',
            new_name='username',
        ),
    ]
